fix format-security error from gcc
Building with `-Werror=format-security` causes several of these errors:

error: format not a string literal and no format arguments [-Werror=format-security]

Let's fix by giving a proper format string.